// Tools and platforms shown on the home page, grouped like the robots list.
// icon: "simple-icons:<slug>" or "lucide:<name>" (inlined by astro-icon at build time),
// or "/icons/<slug>.png" for favicons fetched with scripts/favicons.mjs.
export type StackItem = { name: string; icon: string }
export type StackGroup = { key: "languages" | "robotics" | "ai" | "vision" | "cad" | "embedded" | "web" | "infra" | "tools"; items: StackItem[] }

const si = (slug: string) => `simple-icons:${slug}`
const fav = (slug: string) => `/icons/${slug}.png`

export const STACK: StackGroup[] = [
  {
    key: "languages",
    items: [
      { name: "Python", icon: si("python") },
      { name: "C++", icon: si("cplusplus") },
      { name: "C", icon: si("c") },
      { name: "TypeScript", icon: si("typescript") },
      { name: "JavaScript / Node.js", icon: si("nodedotjs") },
      { name: "Kotlin", icon: si("kotlin") },
      { name: "Java", icon: si("openjdk") },
      { name: "Julia", icon: si("julia") },
      { name: "MATLAB / Simulink", icon: fav("mathworks") },
      { name: "Bash", icon: si("gnubash") },
      { name: "PowerShell", icon: si("powershell") },
      { name: "SQL", icon: "lucide:database" },
      { name: "LaTeX", icon: si("latex") },
      { name: "MicroPython", icon: si("micropython") },
      { name: "URScript", icon: fav("universal-robots") },
      { name: "RAPID", icon: si("abb") },
    ],
  },
  {
    key: "robotics",
    items: [
      { name: "ROS 2", icon: si("ros") },
      { name: "MoveIt 2", icon: fav("moveit") },
      { name: "Nav2 / slam_toolbox", icon: fav("nav2") },
      { name: "RViz", icon: si("ros") },
      { name: "Gazebo", icon: fav("gazebo") },
      { name: "MuJoCo", icon: fav("mujoco") },
      { name: "Cyclone DDS", icon: fav("cyclonedds") },
      { name: "Unitree SDK2", icon: fav("unitree") },
      { name: "NAOqi / libqi", icon: "lucide:bot" },
      { name: "libfranka / franky", icon: fav("franka") },
      { name: "UR RTDE / PolyScope", icon: fav("universal-robots") },
      { name: "xArm SDK", icon: "lucide:hand" },
      { name: "URDF", icon: "lucide:git-branch" },
      { name: "RoboDK", icon: fav("robodk") },
      { name: "ABB RobotStudio", icon: si("abb") },
      { name: "OpenRocket", icon: fav("openrocket") },
      { name: "ANSYS", icon: si("ansys") },
    ],
  },
  {
    key: "ai",
    items: [
      { name: "PyTorch", icon: si("pytorch") },
      { name: "scikit-learn", icon: si("scikitlearn") },
      { name: "XGBoost", icon: fav("xgboost") },
      { name: "NumPy", icon: si("numpy") },
      { name: "pandas", icon: si("pandas") },
      { name: "Jupyter", icon: si("jupyter") },
      { name: "Hugging Face", icon: si("huggingface") },
      { name: "smolagents", icon: si("huggingface") },
      { name: "Ollama", icon: si("ollama") },
      { name: "Qwen", icon: si("qwen") },
      { name: "Llama", icon: si("meta") },
      { name: "Claude & Claude Code", icon: si("claude") },
      { name: "OpenAI Codex", icon: si("openai") },
      { name: "Gemini", icon: si("googlegemini") },
      { name: "MCP", icon: si("modelcontextprotocol") },
      { name: "LiteLLM", icon: fav("litellm") },
      { name: "Docling", icon: fav("docling") },
      { name: "Open WebUI", icon: fav("openwebui") },
      { name: "Streamlit", icon: si("streamlit") },
      { name: "CUDA / TensorRT", icon: si("nvidia") },
    ],
  },
  {
    key: "vision",
    items: [
      { name: "OpenCV", icon: si("opencv") },
      { name: "YOLO / Ultralytics", icon: si("ultralytics") },
      { name: "AprilTag / ArUco", icon: "lucide:scan" },
      { name: "Whisper / faster-whisper", icon: si("openai") },
      { name: "WhisperX", icon: si("github") },
      { name: "Piper TTS", icon: "lucide:mic" },
      { name: "Kokoro TTS", icon: fav("kokoro") },
      { name: "Silero VAD", icon: "lucide:audio-waveform" },
      { name: "Real-ESRGAN", icon: si("github") },
      { name: "WebRTC", icon: si("webrtc") },
    ],
  },
  {
    key: "cad",
    items: [
      { name: "FreeCAD", icon: si("freecad") },
      { name: "Autodesk Inventor", icon: si("autodesk") },
      { name: "SolidWorks", icon: si("dassaultsystemes") },
      { name: "CATIA", icon: si("dassaultsystemes") },
      { name: "Solid Edge", icon: si("siemens") },
      { name: "Creo", icon: fav("ptc") },
      { name: "Minitec iCAD", icon: fav("minitec") },
      { name: "draw.io", icon: si("diagramsdotnet") },
      { name: "PrusaSlicer", icon: fav("prusa") },
      { name: "OrcaSlicer", icon: fav("orcaslicer") },
      { name: "Creality", icon: si("creality") },
    ],
  },
  {
    key: "embedded",
    items: [
      { name: "Arduino", icon: si("arduino") },
      { name: "Portenta H7 / Machine Control", icon: si("arduino") },
      { name: "ESP32", icon: si("espressif") },
      { name: "Teensy", icon: fav("pjrc") },
      { name: "Raspberry Pi", icon: si("raspberrypi") },
      { name: "NVIDIA Jetson", icon: si("nvidia") },
      { name: "PlatformIO", icon: si("platformio") },
      { name: "Modbus RTU / TCP", icon: fav("modbus") },
      { name: "pyserial", icon: "lucide:cable" },
    ],
  },
  {
    key: "web",
    items: [
      { name: "React", icon: si("react") },
      { name: "Next.js", icon: si("nextdotjs") },
      { name: "Astro", icon: si("astro") },
      { name: "Vite", icon: si("vite") },
      { name: "Tailwind CSS", icon: si("tailwindcss") },
      { name: "Three.js", icon: si("threedotjs") },
      { name: "D3", icon: si("d3") },
      { name: "Expo / React Native", icon: si("expo") },
      { name: "Tauri", icon: si("tauri") },
      { name: "FastAPI", icon: si("fastapi") },
      { name: "Flask", icon: si("flask") },
      { name: "Fastify", icon: si("fastify") },
      { name: "Express", icon: si("express") },
      { name: "PyQt", icon: si("qt") },
      { name: "Playwright", icon: si("playwright") },
      { name: "Puppeteer", icon: si("puppeteer") },
      { name: "Firebase", icon: si("firebase") },
      { name: "Supabase", icon: si("supabase") },
      { name: "ZeroMQ", icon: si("zeromq") },
    ],
  },
  {
    key: "infra",
    items: [
      { name: "Linux", icon: si("linux") },
      { name: "Ubuntu", icon: si("ubuntu") },
      { name: "Debian", icon: si("debian") },
      { name: "Docker", icon: si("docker") },
      { name: "systemd", icon: "lucide:cog" },
      { name: "Caddy", icon: si("caddy") },
      { name: "Cloudflare", icon: si("cloudflare") },
      { name: "Tailscale", icon: si("tailscale") },
      { name: "Let's Encrypt", icon: si("letsencrypt") },
      { name: "Git", icon: si("git") },
      { name: "GitHub / Actions", icon: si("github") },
      { name: "GitLab", icon: si("gitlab") },
      { name: "Forgejo", icon: si("forgejo") },
      { name: "Nextcloud", icon: si("nextcloud") },
      { name: "Paperless-ngx", icon: si("paperlessngx") },
      { name: "Immich", icon: si("immich") },
      { name: "Home Assistant", icon: si("homeassistant") },
      { name: "Matrix / Element", icon: si("matrix") },
      { name: "AdGuard Home", icon: si("adguard") },
      { name: "PostgreSQL", icon: si("postgresql") },
      { name: "MariaDB", icon: si("mariadb") },
      { name: "SQLite", icon: si("sqlite") },
      { name: "Redis", icon: si("redis") },
      { name: "DuckDB", icon: si("duckdb") },
      { name: "conda", icon: si("anaconda") },
      { name: "uv", icon: si("uv") },
      { name: "npm", icon: si("npm") },
      { name: "CMake", icon: si("cmake") },
      { name: "Termux", icon: fav("termux") },
      { name: "RustDesk", icon: si("rustdesk") },
      { name: "Windmill", icon: fav("windmill") },
    ],
  },
  {
    key: "tools",
    items: [
      { name: "Obsidian", icon: si("obsidian") },
      { name: "VS Code", icon: si("visualstudiocode") },
      { name: "WezTerm", icon: si("wezterm") },
      { name: "Thunderbird", icon: si("thunderbird") },
      { name: "Bitwarden", icon: si("bitwarden") },
      { name: "ffmpeg", icon: si("ffmpeg") },
      { name: "Overleaf", icon: si("overleaf") },
      { name: "Sphinx", icon: si("sphinx") },
      { name: "Stirling PDF", icon: fav("stirlingpdf") },
      { name: "Apple Shortcuts", icon: si("apple") },
    ],
  },
]
